### ISSUE TITLE
Error loading the 'pgcrypto' Active Record adapter. Missing a gem it depends on?

### ISSUE THREAD

**Issue by sumitdey035** [Plinq/pgcrypto#7]
I added the in the Gemlist when I update the adapter to `pgcrypto` I am getting the above error. Can you please help me with that? I am using rails 6 and ruby 2.6.5

**Comment by jmcbri** [comment]
What are the results when you run 'bundle'?

**Comment by sumitdey035** [comment]
Bundle works fine. No error there. Whenever I try to do DB actions like migrate/rollback this error comes out

```
rake aborted!
LoadError: Error loading the 'pgcrypto' Active Record adapter. Missing a gem it depends on? cannot load such file -- active_record/connection_adapters/pgcrypto_adapter/rails_6
/Users/sumitdey/workspace/weguide_medical/config/environment.rb:5:in `<main>'
/Users/sumitdey/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/sumitdey/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

Caused by:
LoadError: cannot load such file -- active_record/connection_adapters/pgcrypto_adapter/rails_6
/Users/sumitdey/workspace/weguide_medical/config/environment.rb:5:in `<main>'
/Users/sumitdey/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
/Users/sumitdey/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'

Caused by:
Bootsnap::LoadPathCache::FallbackScan: 

Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by yo-gen** [comment]
Will this be worked upon? Any plans for Rails 6 support?

**Comment by ranjithjogi88** [comment]
@yo-gen even i am checking on the same. I have a decryption issue from the rails-6
